[package]
name = "jedit"
version = "0.1.0"
authors = ["EEVV <0eevv0@gmail.com>"]
edition = "2018"

[dependencies]
jwin = {git = "https://github.com/EEVV/jwin"}
jvec = {git = "https://github.com/EEVV/jvec"}